#platform :ios, "8.0"
source 'https://github.com/CocoaPods/Specs.git'

target 'DroiPushDemo' do

pod 'DroiPushSDK'
pod 'DroiCoreSDK'
post_install do |installer|
require './Pods/DroiCoreSDK/scripts/postInstall.rb'
DroiCoreParser.installParser()
end

end
